version: '3.8'

services:
  node01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    networks:
      - network
    ports:
      - 9200:9200
    container_name: ecommerce-es
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=123456789
  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.1
    networks:
      - network
    ports:
      - 5601:5601
    container_name: ecommere-kib
    depends_on:
      - node01
networks:
  network:
